apiVersion: v1
kind: Pod
metadata:
  name: go-app
  namespace: dev
  labels:
    app: go-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  containers:
  - name: go-app
    image: kessis01/go-app